image: maven:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp
  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

cache:
  paths:
    - maven.repository/

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - mvn compile

unit-test:
  stage: test
  script:
    - mvn test

integration-test:
  stage: integration-test
  services:
    - postgres:9.6
  script:
    - mvn -P test-business,test-consumer clean verify sonar:sonar