image: maven:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - mvn compile

unit-test:
  stage: test
  script:
    - mvn test

integration-test:
  stage: integration-test
  services:
    - postgres:9.6
  script:
    - mvn -P test-business,test-consumer clean verify sonar:sonar