image: maven:latest

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test
  - report

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

report:
  stage: report
  script:
    - mvn verify sonar:sonar