image: maven:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test
  - integration-test
  - report

build:
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  dependencies:
    - build
  script:
    - mvn test
  artifacts:
    paths:
      - target/

integration-test:
  stage: integration-test
  services:
    - postgres:9.6
  script:
    - mvn -P test-business,test-consumer clean install

report:
  stage: report
  dependencies:
    - build
  script:
    - mvn verify sonar:sonar