image: maven:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test
  - integration-test
  - report

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

integration-test:
  stage: integration-test
  services:
    - name: postgres:alpine
      command: ["sh", "-c", "/bin/su", "-", "postgres", "postgres", "&&", "psql", "-U","$POSTGRES_USER", "--password",
                "$POSTGRES_PASSWORD", "$POSTGRES_DB", "<", "./DB-Docker/dev/db/init/docker-entrypoint-initdb.d/01_create_schema.sql" ]
  script:
    - mvn -P test-business,test-consumer clean install

report:
  stage: report
  script:
    - mvn verify sonar:sonar