variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

cache:
  paths:
    - /.m2/repository

stages:
  - build
  - test
  - integration-test
  - report

validate:jdk8:
  stage: build
  script:
    - mvn compile
  image: maven:3.5.0-jdk-8

unit-test:jdk8:
  stage: test
  script:
    - mvn test
  image: maven:3.5.0-jdk-8

integration-test:jdk8:
  stage: integration-test
  services:
    - postgres:9.6
  script:
    - mvn -P test-business,test-consumer clean install
  image: maven:3.5.0-jdk-8

report:
  stage: report
  script:
    - mvn verify sonar:sonar
  image: maven:3.5.0-jdk-8
