variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

cache:
  paths:
    - root/.m2/repository
    - target/

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - mvn compile
  image: maven:3.5.0-jdk-8

unit-test:
  stage: test
  script:
    - mvn test
  image: maven:3.5.0-jdk-8

integration-test:
  stage: integration-test
  services:
    - postgres:9.6
  script:
#    - mvn -P test-business,test-consumer clean verify sonar:sonar
    - mvn -P test-business,test-consumer failsafe:integration-test
  image: maven:3.5.0-jdk-8
