image: maven:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    expire_in: 10 min
    paths:
      - "*/target"

unit-test:
  stage: test
  script:
    - find . -name "*.class" -exec touch {} \+
    - mvn $MAVEN_CLI_OPTS test

integration-test:
  stage: integration-test
  services:
    - postgres:9.6
  script:
    - find . -name "*.class" -exec touch {} \+
    - mvn $MAVEN_CLI_OPTS -P test-business,test-consumer clean verify sonar:sonar