image: maven:latest

stages:
  - build
  - test
  - integration-test
  - report

build:
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  dependencies:
    - build
  script:
    - mvn test
  artifacts:
    paths:
      - target/

integration-test:
  stage: integration-test
  dependencies:
    - build
#  before_script:
#    - cd DB-Docker/dev/
#    - docker-compose up
  script:
    - mvn -P test-business,test-consumer clean install
  artifacts:
    paths:
      - target/

report:
  stage: report
  dependencies:
    - build
  script:
    - mvn verify sonar:sonar
  artifacts:
    paths:
      - target/