image: maven:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test
  - integration-test
  - report

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

integration-test:
  stage: integration-test
  services:
    - postgres:alpine
  script:
    - mvn -P test-business,test-consumer clean install

report:
  stage: report
  script:
    - mvn verify sonar:sonar